import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "./components/BootstrapClient";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "frontEnd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="container-fluid">
          <div className="row">
            <div className="col-12">
              <Navigation />
            </div>
          </div>
          <BootstrapClient />
          {children}
          <div className="row">
            <div className="col-12">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}