import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

import { Prompt } from "next/font/google";
import { BootstrapClient } from "./components/BootstrapClient";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
import { AuthProvider } from "./context/AuthContext";
import 'sweetalert2/dist/sweetalert2.min.css';

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-prompt",
  display: "swap",
});

export const metadata = {
  title: "frontEnd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th" className={prompt.variable}>
      <body className="antialiased" style={{ fontFamily: "var(--font-prompt)" }}>
        <AuthProvider>
          <div className="container-fluid min-vh-100 d-flex flex-column">
            <Navigation />
            <main className="flex-grow-1">
              <BootstrapClient />
              {children}
            </main>
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
